version: '3.8'

services:
  app:
    build: .
    container_name: nest_app
    ports:
      - 3002:3002
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydatabase?schema=public
    depends_on:
      - prometheus
      - grafana
      - postgres
    command: npm run start:prod
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - app-network

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  grafana-storage:
  postgres-data:

networks:
  app-network:
